version: '3.8'
services:
  zookeeper-lucero:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  postgres-lucero:
    image: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=learning_reactive_r2dbc
    ports:
      - "5432:5432"
  mongodb-lucero:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=learning_reactive_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
  redis-lucero:
    image: 'redis:latest'
    ports:
      - "6379:6379"
  kafka-lucero:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-lucero:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-lucero:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper-lucero
  api-lucero:
    environment:
      - APPLICATION_PORT=8083
      - POSTGRES_USER=postgresql
      - POSTGRES_PASS=postgresql
      - POSTGRES_HOST=postgres-lucero
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=learning_reactive_r2dbc
      - MONGO_USER=mongodb
      - MONGO_PASS=mongodb
      - MONGO_HOST=mongodb-lucero:27017
      - MONGO_DB_NAME=learning_reactive_mongo
      - REDIS_HOST=redis-lucero
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka-lucero:9092
      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - postgres-lucero
      - mongodb-lucero
      - redis-lucero
      - kafka-lucero